/**
 * generated by Xtext 2.16.0
 */
package org.unipampa.lesse.xCanopus.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.unipampa.lesse.xCanopus.XCanopusPackage;
import org.unipampa.lesse.xCanopus.and_atleast;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>and atleast</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.unipampa.lesse.xCanopus.impl.and_atleastImpl#getInteger1 <em>Integer1</em>}</li>
 *   <li>{@link org.unipampa.lesse.xCanopus.impl.and_atleastImpl#getInteger2 <em>Integer2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class and_atleastImpl extends STEPSImpl implements and_atleast
{
  /**
   * The default value of the '{@link #getInteger1() <em>Integer1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInteger1()
   * @generated
   * @ordered
   */
  protected static final int INTEGER1_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getInteger1() <em>Integer1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInteger1()
   * @generated
   * @ordered
   */
  protected int integer1 = INTEGER1_EDEFAULT;

  /**
   * The default value of the '{@link #getInteger2() <em>Integer2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInteger2()
   * @generated
   * @ordered
   */
  protected static final int INTEGER2_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getInteger2() <em>Integer2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInteger2()
   * @generated
   * @ordered
   */
  protected int integer2 = INTEGER2_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected and_atleastImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XCanopusPackage.Literals.AND_ATLEAST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getInteger1()
  {
    return integer1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInteger1(int newInteger1)
  {
    int oldInteger1 = integer1;
    integer1 = newInteger1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XCanopusPackage.AND_ATLEAST__INTEGER1, oldInteger1, integer1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getInteger2()
  {
    return integer2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInteger2(int newInteger2)
  {
    int oldInteger2 = integer2;
    integer2 = newInteger2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XCanopusPackage.AND_ATLEAST__INTEGER2, oldInteger2, integer2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XCanopusPackage.AND_ATLEAST__INTEGER1:
        return getInteger1();
      case XCanopusPackage.AND_ATLEAST__INTEGER2:
        return getInteger2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XCanopusPackage.AND_ATLEAST__INTEGER1:
        setInteger1((Integer)newValue);
        return;
      case XCanopusPackage.AND_ATLEAST__INTEGER2:
        setInteger2((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XCanopusPackage.AND_ATLEAST__INTEGER1:
        setInteger1(INTEGER1_EDEFAULT);
        return;
      case XCanopusPackage.AND_ATLEAST__INTEGER2:
        setInteger2(INTEGER2_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XCanopusPackage.AND_ATLEAST__INTEGER1:
        return integer1 != INTEGER1_EDEFAULT;
      case XCanopusPackage.AND_ATLEAST__INTEGER2:
        return integer2 != INTEGER2_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (integer1: ");
    result.append(integer1);
    result.append(", integer2: ");
    result.append(integer2);
    result.append(')');
    return result.toString();
  }

} //and_atleastImpl
