/**
 * generated by Xtext 2.15.0
 */
package org.unipampa.lesse.xCanopus.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.unipampa.lesse.xCanopus.HARDWARE;
import org.unipampa.lesse.xCanopus.MetricModel;
import org.unipampa.lesse.xCanopus.SUT;
import org.unipampa.lesse.xCanopus.SUT_TYPE;
import org.unipampa.lesse.xCanopus.XCanopusPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SUT</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.unipampa.lesse.xCanopus.impl.SUTImpl#getHostname <em>Hostname</em>}</li>
 *   <li>{@link org.unipampa.lesse.xCanopus.impl.SUTImpl#getIp <em>Ip</em>}</li>
 *   <li>{@link org.unipampa.lesse.xCanopus.impl.SUTImpl#getHardware <em>Hardware</em>}</li>
 *   <li>{@link org.unipampa.lesse.xCanopus.impl.SUTImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.unipampa.lesse.xCanopus.impl.SUTImpl#getSut <em>Sut</em>}</li>
 *   <li>{@link org.unipampa.lesse.xCanopus.impl.SUTImpl#getMetricmodel <em>Metricmodel</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SUTImpl extends MinimalEObjectImpl.Container implements SUT
{
  /**
   * The default value of the '{@link #getHostname() <em>Hostname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHostname()
   * @generated
   * @ordered
   */
  protected static final String HOSTNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHostname() <em>Hostname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHostname()
   * @generated
   * @ordered
   */
  protected String hostname = HOSTNAME_EDEFAULT;

  /**
   * The default value of the '{@link #getIp() <em>Ip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIp()
   * @generated
   * @ordered
   */
  protected static final String IP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIp() <em>Ip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIp()
   * @generated
   * @ordered
   */
  protected String ip = IP_EDEFAULT;

  /**
   * The default value of the '{@link #getHardware() <em>Hardware</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHardware()
   * @generated
   * @ordered
   */
  protected static final HARDWARE HARDWARE_EDEFAULT = HARDWARE.PHYSICAL_MACHINE;

  /**
   * The cached value of the '{@link #getHardware() <em>Hardware</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHardware()
   * @generated
   * @ordered
   */
  protected HARDWARE hardware = HARDWARE_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final SUT_TYPE TYPE_EDEFAULT = SUT_TYPE.DESKTOPAPP;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected SUT_TYPE type = TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getSut() <em>Sut</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSut()
   * @generated
   * @ordered
   */
  protected EList<SUT> sut;

  /**
   * The cached value of the '{@link #getMetricmodel() <em>Metricmodel</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetricmodel()
   * @generated
   * @ordered
   */
  protected MetricModel metricmodel;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SUTImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XCanopusPackage.Literals.SUT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getHostname()
  {
    return hostname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHostname(String newHostname)
  {
    String oldHostname = hostname;
    hostname = newHostname;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XCanopusPackage.SUT__HOSTNAME, oldHostname, hostname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIp()
  {
    return ip;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIp(String newIp)
  {
    String oldIp = ip;
    ip = newIp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XCanopusPackage.SUT__IP, oldIp, ip));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HARDWARE getHardware()
  {
    return hardware;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHardware(HARDWARE newHardware)
  {
    HARDWARE oldHardware = hardware;
    hardware = newHardware == null ? HARDWARE_EDEFAULT : newHardware;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XCanopusPackage.SUT__HARDWARE, oldHardware, hardware));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SUT_TYPE getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(SUT_TYPE newType)
  {
    SUT_TYPE oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XCanopusPackage.SUT__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<SUT> getSut()
  {
    if (sut == null)
    {
      sut = new EObjectResolvingEList<SUT>(SUT.class, this, XCanopusPackage.SUT__SUT);
    }
    return sut;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MetricModel getMetricmodel()
  {
    if (metricmodel != null && metricmodel.eIsProxy())
    {
      InternalEObject oldMetricmodel = (InternalEObject)metricmodel;
      metricmodel = (MetricModel)eResolveProxy(oldMetricmodel);
      if (metricmodel != oldMetricmodel)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, XCanopusPackage.SUT__METRICMODEL, oldMetricmodel, metricmodel));
      }
    }
    return metricmodel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MetricModel basicGetMetricmodel()
  {
    return metricmodel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMetricmodel(MetricModel newMetricmodel)
  {
    MetricModel oldMetricmodel = metricmodel;
    metricmodel = newMetricmodel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XCanopusPackage.SUT__METRICMODEL, oldMetricmodel, metricmodel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XCanopusPackage.SUT__HOSTNAME:
        return getHostname();
      case XCanopusPackage.SUT__IP:
        return getIp();
      case XCanopusPackage.SUT__HARDWARE:
        return getHardware();
      case XCanopusPackage.SUT__TYPE:
        return getType();
      case XCanopusPackage.SUT__SUT:
        return getSut();
      case XCanopusPackage.SUT__METRICMODEL:
        if (resolve) return getMetricmodel();
        return basicGetMetricmodel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XCanopusPackage.SUT__HOSTNAME:
        setHostname((String)newValue);
        return;
      case XCanopusPackage.SUT__IP:
        setIp((String)newValue);
        return;
      case XCanopusPackage.SUT__HARDWARE:
        setHardware((HARDWARE)newValue);
        return;
      case XCanopusPackage.SUT__TYPE:
        setType((SUT_TYPE)newValue);
        return;
      case XCanopusPackage.SUT__SUT:
        getSut().clear();
        getSut().addAll((Collection<? extends SUT>)newValue);
        return;
      case XCanopusPackage.SUT__METRICMODEL:
        setMetricmodel((MetricModel)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XCanopusPackage.SUT__HOSTNAME:
        setHostname(HOSTNAME_EDEFAULT);
        return;
      case XCanopusPackage.SUT__IP:
        setIp(IP_EDEFAULT);
        return;
      case XCanopusPackage.SUT__HARDWARE:
        setHardware(HARDWARE_EDEFAULT);
        return;
      case XCanopusPackage.SUT__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case XCanopusPackage.SUT__SUT:
        getSut().clear();
        return;
      case XCanopusPackage.SUT__METRICMODEL:
        setMetricmodel((MetricModel)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XCanopusPackage.SUT__HOSTNAME:
        return HOSTNAME_EDEFAULT == null ? hostname != null : !HOSTNAME_EDEFAULT.equals(hostname);
      case XCanopusPackage.SUT__IP:
        return IP_EDEFAULT == null ? ip != null : !IP_EDEFAULT.equals(ip);
      case XCanopusPackage.SUT__HARDWARE:
        return hardware != HARDWARE_EDEFAULT;
      case XCanopusPackage.SUT__TYPE:
        return type != TYPE_EDEFAULT;
      case XCanopusPackage.SUT__SUT:
        return sut != null && !sut.isEmpty();
      case XCanopusPackage.SUT__METRICMODEL:
        return metricmodel != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (hostname: ");
    result.append(hostname);
    result.append(", ip: ");
    result.append(ip);
    result.append(", hardware: ");
    result.append(hardware);
    result.append(", type: ");
    result.append(type);
    result.append(')');
    return result.toString();
  }

} //SUTImpl
