/**
 * generated by Xtext 2.15.0
 */
package org.unipampa.lesse.xCanopus.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.unipampa.lesse.xCanopus.COUNTER_TRANSACTION;
import org.unipampa.lesse.xCanopus.TransactionCounter;
import org.unipampa.lesse.xCanopus.XCanopusPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Transaction Counter</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.unipampa.lesse.xCanopus.impl.TransactionCounterImpl#getCounterTransaction <em>Counter Transaction</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TransactionCounterImpl extends CounterImpl implements TransactionCounter
{
  /**
   * The cached value of the '{@link #getCounterTransaction() <em>Counter Transaction</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCounterTransaction()
   * @generated
   * @ordered
   */
  protected EList<COUNTER_TRANSACTION> counterTransaction;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TransactionCounterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XCanopusPackage.Literals.TRANSACTION_COUNTER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<COUNTER_TRANSACTION> getCounterTransaction()
  {
    if (counterTransaction == null)
    {
      counterTransaction = new EDataTypeEList<COUNTER_TRANSACTION>(COUNTER_TRANSACTION.class, this, XCanopusPackage.TRANSACTION_COUNTER__COUNTER_TRANSACTION);
    }
    return counterTransaction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XCanopusPackage.TRANSACTION_COUNTER__COUNTER_TRANSACTION:
        return getCounterTransaction();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XCanopusPackage.TRANSACTION_COUNTER__COUNTER_TRANSACTION:
        getCounterTransaction().clear();
        getCounterTransaction().addAll((Collection<? extends COUNTER_TRANSACTION>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XCanopusPackage.TRANSACTION_COUNTER__COUNTER_TRANSACTION:
        getCounterTransaction().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XCanopusPackage.TRANSACTION_COUNTER__COUNTER_TRANSACTION:
        return counterTransaction != null && !counterTransaction.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (counterTransaction: ");
    result.append(counterTransaction);
    result.append(')');
    return result.toString();
  }

} //TransactionCounterImpl
