/**
 * generated by Xtext 2.15.0
 */
package org.unipampa.lesse.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.unipampa.lesse.XCanopusRuntimeModule;
import org.unipampa.lesse.XCanopusStandaloneSetup;
import org.unipampa.lesse.ide.XCanopusIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class XCanopusIdeSetup extends XCanopusStandaloneSetup {
  @Override
  public Injector createInjector() {
    XCanopusRuntimeModule _xCanopusRuntimeModule = new XCanopusRuntimeModule();
    XCanopusIdeModule _xCanopusIdeModule = new XCanopusIdeModule();
    return Guice.createInjector(Modules2.mixin(_xCanopusRuntimeModule, _xCanopusIdeModule));
  }
}
