/*
 * generated by Xtext 2.16.0
 */
package org.unipampa.lesse.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.unipampa.lesse.XCanopus.ui.internal.XCanopusActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XCanopusExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(XCanopusActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		XCanopusActivator activator = XCanopusActivator.getInstance();
		return activator != null ? activator.getInjector(XCanopusActivator.ORG_UNIPAMPA_LESSE_XCANOPUS) : null;
	}

}
