/**
 * generated by Xtext 2.15.0
 */
package org.unipampa.lesse;

import org.unipampa.lesse.AbstractXCanopusRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class XCanopusRuntimeModule extends AbstractXCanopusRuntimeModule {
}
