/**
 * generated by Xtext 2.16.0
 */
package org.unipampa.lesse.xCanopus;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AND</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getAND()
 * @model
 * @generated
 */
public interface AND extends CONDITION
{
} // AND
