/**
 * generated by Xtext 2.16.0
 */
package org.unipampa.lesse.xCanopus;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>and the scenario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unipampa.lesse.xCanopus.and_the_scenario#getScenario <em>Scenario</em>}</li>
 * </ul>
 *
 * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getand_the_scenario()
 * @model
 * @generated
 */
public interface and_the_scenario extends STEPS
{
  /**
   * Returns the value of the '<em><b>Scenario</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scenario</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenario</em>' reference.
   * @see #setScenario(SCENARIO)
   * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getand_the_scenario_Scenario()
   * @model
   * @generated
   */
  SCENARIO getScenario();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.xCanopus.and_the_scenario#getScenario <em>Scenario</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scenario</em>' reference.
   * @see #getScenario()
   * @generated
   */
  void setScenario(SCENARIO value);

} // and_the_scenario
