/**
 * generated by Xtext 2.16.0
 */
package org.unipampa.lesse.xCanopus;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CONDITION</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unipampa.lesse.xCanopus.CONDITION#getPost <em>Post</em>}</li>
 * </ul>
 *
 * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getCONDITION()
 * @model
 * @generated
 */
public interface CONDITION extends EObject
{
  /**
   * Returns the value of the '<em><b>Post</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Post</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post</em>' containment reference.
   * @see #setPost(POSTCONDITION)
   * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getCONDITION_Post()
   * @model containment="true"
   * @generated
   */
  POSTCONDITION getPost();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.xCanopus.CONDITION#getPost <em>Post</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Post</em>' containment reference.
   * @see #getPost()
   * @generated
   */
  void setPost(POSTCONDITION value);

} // CONDITION
