/**
 * generated by Xtext 2.16.0
 */
package org.unipampa.lesse.xCanopus;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>METRICTYPEMONITORED</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getMETRICTYPEMONITORED()
 * @model
 * @generated
 */
public enum METRICTYPEMONITORED implements Enumerator
{
  /**
   * The '<em><b>MEMORY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MEMORY_VALUE
   * @generated
   * @ordered
   */
  MEMORY(0, "MEMORY", "memory"),

  /**
   * The '<em><b>DISK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DISK_VALUE
   * @generated
   * @ordered
   */
  DISK(1, "DISK", "disk"),

  /**
   * The '<em><b>WEBRESOURCES</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WEBRESOURCES_VALUE
   * @generated
   * @ordered
   */
  WEBRESOURCES(2, "WEBRESOURCES", "web resources"),

  /**
   * The '<em><b>TRANSACTION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TRANSACTION_VALUE
   * @generated
   * @ordered
   */
  TRANSACTION(3, "TRANSACTION", "transaction"),

  /**
   * The '<em><b>PROCESSOR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PROCESSOR_VALUE
   * @generated
   * @ordered
   */
  PROCESSOR(4, "PROCESSOR", "processor");

  /**
   * The '<em><b>MEMORY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>MEMORY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MEMORY
   * @model literal="memory"
   * @generated
   * @ordered
   */
  public static final int MEMORY_VALUE = 0;

  /**
   * The '<em><b>DISK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DISK</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DISK
   * @model literal="disk"
   * @generated
   * @ordered
   */
  public static final int DISK_VALUE = 1;

  /**
   * The '<em><b>WEBRESOURCES</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WEBRESOURCES</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WEBRESOURCES
   * @model literal="web resources"
   * @generated
   * @ordered
   */
  public static final int WEBRESOURCES_VALUE = 2;

  /**
   * The '<em><b>TRANSACTION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TRANSACTION</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TRANSACTION
   * @model literal="transaction"
   * @generated
   * @ordered
   */
  public static final int TRANSACTION_VALUE = 3;

  /**
   * The '<em><b>PROCESSOR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PROCESSOR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PROCESSOR
   * @model literal="processor"
   * @generated
   * @ordered
   */
  public static final int PROCESSOR_VALUE = 4;

  /**
   * An array of all the '<em><b>METRICTYPEMONITORED</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final METRICTYPEMONITORED[] VALUES_ARRAY =
    new METRICTYPEMONITORED[]
    {
      MEMORY,
      DISK,
      WEBRESOURCES,
      TRANSACTION,
      PROCESSOR,
    };

  /**
   * A public read-only list of all the '<em><b>METRICTYPEMONITORED</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<METRICTYPEMONITORED> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>METRICTYPEMONITORED</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static METRICTYPEMONITORED get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      METRICTYPEMONITORED result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>METRICTYPEMONITORED</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static METRICTYPEMONITORED getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      METRICTYPEMONITORED result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>METRICTYPEMONITORED</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static METRICTYPEMONITORED get(int value)
  {
    switch (value)
    {
      case MEMORY_VALUE: return MEMORY;
      case DISK_VALUE: return DISK;
      case WEBRESOURCES_VALUE: return WEBRESOURCES;
      case TRANSACTION_VALUE: return TRANSACTION;
      case PROCESSOR_VALUE: return PROCESSOR;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private METRICTYPEMONITORED(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //METRICTYPEMONITORED
