/**
 * generated by Xtext 2.16.0
 */
package org.unipampa.lesse.xCanopus;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>POSTCONDITION</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unipampa.lesse.xCanopus.POSTCONDITION#getWGT <em>WGT</em>}</li>
 *   <li>{@link org.unipampa.lesse.xCanopus.POSTCONDITION#getTHE <em>THE</em>}</li>
 *   <li>{@link org.unipampa.lesse.xCanopus.POSTCONDITION#getATL <em>ATL</em>}</li>
 * </ul>
 *
 * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getPOSTCONDITION()
 * @model
 * @generated
 */
public interface POSTCONDITION extends EObject
{
  /**
   * Returns the value of the '<em><b>WGT</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>WGT</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>WGT</em>' attribute.
   * @see #setWGT(String)
   * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getPOSTCONDITION_WGT()
   * @model
   * @generated
   */
  String getWGT();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.xCanopus.POSTCONDITION#getWGT <em>WGT</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>WGT</em>' attribute.
   * @see #getWGT()
   * @generated
   */
  void setWGT(String value);

  /**
   * Returns the value of the '<em><b>THE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>THE</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>THE</em>' attribute.
   * @see #setTHE(String)
   * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getPOSTCONDITION_THE()
   * @model
   * @generated
   */
  String getTHE();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.xCanopus.POSTCONDITION#getTHE <em>THE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>THE</em>' attribute.
   * @see #getTHE()
   * @generated
   */
  void setTHE(String value);

  /**
   * Returns the value of the '<em><b>ATL</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>ATL</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>ATL</em>' attribute.
   * @see #setATL(String)
   * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getPOSTCONDITION_ATL()
   * @model
   * @generated
   */
  String getATL();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.xCanopus.POSTCONDITION#getATL <em>ATL</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>ATL</em>' attribute.
   * @see #getATL()
   * @generated
   */
  void setATL(String value);

} // POSTCONDITION
