/**
 * generated by Xtext 2.16.0
 */
package org.unipampa.lesse.xCanopus;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>STEPS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getSTEPS()
 * @model
 * @generated
 */
public interface STEPS extends EObject
{
} // STEPS
