/**
 * generated by Xtext 2.15.0
 */
package org.unipampa.lesse.xCanopus;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transaction Counter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unipampa.lesse.xCanopus.TransactionCounter#getCounterTransaction <em>Counter Transaction</em>}</li>
 * </ul>
 *
 * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getTransactionCounter()
 * @model
 * @generated
 */
public interface TransactionCounter extends Counter
{
  /**
   * Returns the value of the '<em><b>Counter Transaction</b></em>' attribute list.
   * The list contents are of type {@link org.unipampa.lesse.xCanopus.COUNTER_TRANSACTION}.
   * The literals are from the enumeration {@link org.unipampa.lesse.xCanopus.COUNTER_TRANSACTION}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Counter Transaction</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Counter Transaction</em>' attribute list.
   * @see org.unipampa.lesse.xCanopus.COUNTER_TRANSACTION
   * @see org.unipampa.lesse.xCanopus.XCanopusPackage#getTransactionCounter_CounterTransaction()
   * @model unique="false"
   * @generated
   */
  EList<COUNTER_TRANSACTION> getCounterTransaction();

} // TransactionCounter
