/**
 * generated by Xtext 2.16.0
 */
package org.unipampa.lesse.xCanopus;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.unipampa.lesse.xCanopus.XCanopusFactory
 * @model kind="package"
 * @generated
 */
public interface XCanopusPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xCanopus";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.unipampa.org/lesse/XCanopus";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xCanopus";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XCanopusPackage eINSTANCE = org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl.init();

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.ModelImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Main</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MAIN = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.MetricModelImpl <em>Metric Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.MetricModelImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getMetricModel()
   * @generated
   */
  int METRIC_MODEL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_MODEL__STEPS = 1;

  /**
   * The number of structural features of the '<em>Metric Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.MainImpl <em>Main</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.MainImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getMain()
   * @generated
   */
  int MAIN = 2;

  /**
   * The feature id for the '<em><b>Main</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__MAIN = 0;

  /**
   * The number of structural features of the '<em>Main</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.STEPSImpl <em>STEPS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.STEPSImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getSTEPS()
   * @generated
   */
  int STEPS = 3;

  /**
   * The number of structural features of the '<em>STEPS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.and_workloadImpl <em>and workload</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.and_workloadImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getand_workload()
   * @generated
   */
  int AND_WORKLOAD = 4;

  /**
   * The feature id for the '<em><b>Sut1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_WORKLOAD__SUT1 = STEPS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Suttype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_WORKLOAD__SUTTYPE = STEPS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sut2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_WORKLOAD__SUT2 = STEPS_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>and workload</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_WORKLOAD_FEATURE_COUNT = STEPS_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.and_the_scenarioImpl <em>and the scenario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.and_the_scenarioImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getand_the_scenario()
   * @generated
   */
  int AND_THE_SCENARIO = 5;

  /**
   * The feature id for the '<em><b>Scenario</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_THE_SCENARIO__SCENARIO = STEPS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>and the scenario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_THE_SCENARIO_FEATURE_COUNT = STEPS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.and_atleastImpl <em>and atleast</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.and_atleastImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getand_atleast()
   * @generated
   */
  int AND_ATLEAST = 6;

  /**
   * The feature id for the '<em><b>Integer1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_ATLEAST__INTEGER1 = STEPS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Integer2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_ATLEAST__INTEGER2 = STEPS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>and atleast</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_ATLEAST_FEATURE_COUNT = STEPS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.and_the_metricImpl <em>and the metric</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.and_the_metricImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getand_the_metric()
   * @generated
   */
  int AND_THE_METRIC = 7;

  /**
   * The feature id for the '<em><b>Metric</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_THE_METRIC__METRIC = STEPS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Integer1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_THE_METRIC__INTEGER1 = STEPS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Integer2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_THE_METRIC__INTEGER2 = STEPS_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Integer3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_THE_METRIC__INTEGER3 = STEPS_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>and the metric</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_THE_METRIC_FEATURE_COUNT = STEPS_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.whenImpl <em>when</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.whenImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getwhen()
   * @generated
   */
  int WHEN = 8;

  /**
   * The feature id for the '<em><b>Metrictype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__METRICTYPE = STEPS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>when</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN_FEATURE_COUNT = STEPS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.thenImpl <em>then</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.thenImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getthen()
   * @generated
   */
  int THEN = 9;

  /**
   * The feature id for the '<em><b>Metric</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__METRIC = STEPS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Integer1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__INTEGER1 = STEPS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Integer2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__INTEGER2 = STEPS_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Integer3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__INTEGER3 = STEPS_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>then</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN_FEATURE_COUNT = STEPS_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.givenImpl <em>given</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.givenImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getgiven()
   * @generated
   */
  int GIVEN = 10;

  /**
   * The feature id for the '<em><b>Sut1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN__SUT1 = STEPS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Suttype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN__SUTTYPE = STEPS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sut2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN__SUT2 = STEPS_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>given</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN_FEATURE_COUNT = STEPS_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.SCENARIOImpl <em>SCENARIO</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.SCENARIOImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getSCENARIO()
   * @generated
   */
  int SCENARIO = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__NAME = 0;

  /**
   * The number of structural features of the '<em>SCENARIO</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.impl.SUTImpl <em>SUT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.impl.SUTImpl
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getSUT()
   * @generated
   */
  int SUT = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUT__NAME = 0;

  /**
   * The number of structural features of the '<em>SUT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.METRICTYPEMONITORED <em>METRICTYPEMONITORED</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.METRICTYPEMONITORED
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getMETRICTYPEMONITORED()
   * @generated
   */
  int METRICTYPEMONITORED = 13;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.METRICTYPE <em>METRICTYPE</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.METRICTYPE
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getMETRICTYPE()
   * @generated
   */
  int METRICTYPE = 14;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.HARDWARE <em>HARDWARE</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.HARDWARE
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getHARDWARE()
   * @generated
   */
  int HARDWARE = 15;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.xCanopus.SUT_TYPE <em>SUT TYPE</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.xCanopus.SUT_TYPE
   * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getSUT_TYPE()
   * @generated
   */
  int SUT_TYPE = 16;


  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.unipampa.lesse.xCanopus.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.unipampa.lesse.xCanopus.Model#getMain <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Main</em>'.
   * @see org.unipampa.lesse.xCanopus.Model#getMain()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Main();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.MetricModel <em>Metric Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metric Model</em>'.
   * @see org.unipampa.lesse.xCanopus.MetricModel
   * @generated
   */
  EClass getMetricModel();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.MetricModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.unipampa.lesse.xCanopus.MetricModel#getName()
   * @see #getMetricModel()
   * @generated
   */
  EAttribute getMetricModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.unipampa.lesse.xCanopus.MetricModel#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see org.unipampa.lesse.xCanopus.MetricModel#getSteps()
   * @see #getMetricModel()
   * @generated
   */
  EReference getMetricModel_Steps();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.Main <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main</em>'.
   * @see org.unipampa.lesse.xCanopus.Main
   * @generated
   */
  EClass getMain();

  /**
   * Returns the meta object for the containment reference list '{@link org.unipampa.lesse.xCanopus.Main#getMain <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Main</em>'.
   * @see org.unipampa.lesse.xCanopus.Main#getMain()
   * @see #getMain()
   * @generated
   */
  EReference getMain_Main();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.STEPS <em>STEPS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>STEPS</em>'.
   * @see org.unipampa.lesse.xCanopus.STEPS
   * @generated
   */
  EClass getSTEPS();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.and_workload <em>and workload</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>and workload</em>'.
   * @see org.unipampa.lesse.xCanopus.and_workload
   * @generated
   */
  EClass getand_workload();

  /**
   * Returns the meta object for the reference '{@link org.unipampa.lesse.xCanopus.and_workload#getSut1 <em>Sut1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sut1</em>'.
   * @see org.unipampa.lesse.xCanopus.and_workload#getSut1()
   * @see #getand_workload()
   * @generated
   */
  EReference getand_workload_Sut1();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.and_workload#getSuttype <em>Suttype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Suttype</em>'.
   * @see org.unipampa.lesse.xCanopus.and_workload#getSuttype()
   * @see #getand_workload()
   * @generated
   */
  EAttribute getand_workload_Suttype();

  /**
   * Returns the meta object for the reference '{@link org.unipampa.lesse.xCanopus.and_workload#getSut2 <em>Sut2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sut2</em>'.
   * @see org.unipampa.lesse.xCanopus.and_workload#getSut2()
   * @see #getand_workload()
   * @generated
   */
  EReference getand_workload_Sut2();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.and_the_scenario <em>and the scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>and the scenario</em>'.
   * @see org.unipampa.lesse.xCanopus.and_the_scenario
   * @generated
   */
  EClass getand_the_scenario();

  /**
   * Returns the meta object for the reference '{@link org.unipampa.lesse.xCanopus.and_the_scenario#getScenario <em>Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Scenario</em>'.
   * @see org.unipampa.lesse.xCanopus.and_the_scenario#getScenario()
   * @see #getand_the_scenario()
   * @generated
   */
  EReference getand_the_scenario_Scenario();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.and_atleast <em>and atleast</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>and atleast</em>'.
   * @see org.unipampa.lesse.xCanopus.and_atleast
   * @generated
   */
  EClass getand_atleast();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.and_atleast#getInteger1 <em>Integer1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integer1</em>'.
   * @see org.unipampa.lesse.xCanopus.and_atleast#getInteger1()
   * @see #getand_atleast()
   * @generated
   */
  EAttribute getand_atleast_Integer1();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.and_atleast#getInteger2 <em>Integer2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integer2</em>'.
   * @see org.unipampa.lesse.xCanopus.and_atleast#getInteger2()
   * @see #getand_atleast()
   * @generated
   */
  EAttribute getand_atleast_Integer2();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.and_the_metric <em>and the metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>and the metric</em>'.
   * @see org.unipampa.lesse.xCanopus.and_the_metric
   * @generated
   */
  EClass getand_the_metric();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.and_the_metric#getMetric <em>Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Metric</em>'.
   * @see org.unipampa.lesse.xCanopus.and_the_metric#getMetric()
   * @see #getand_the_metric()
   * @generated
   */
  EAttribute getand_the_metric_Metric();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.and_the_metric#getInteger1 <em>Integer1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integer1</em>'.
   * @see org.unipampa.lesse.xCanopus.and_the_metric#getInteger1()
   * @see #getand_the_metric()
   * @generated
   */
  EAttribute getand_the_metric_Integer1();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.and_the_metric#getInteger2 <em>Integer2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integer2</em>'.
   * @see org.unipampa.lesse.xCanopus.and_the_metric#getInteger2()
   * @see #getand_the_metric()
   * @generated
   */
  EAttribute getand_the_metric_Integer2();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.and_the_metric#getInteger3 <em>Integer3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integer3</em>'.
   * @see org.unipampa.lesse.xCanopus.and_the_metric#getInteger3()
   * @see #getand_the_metric()
   * @generated
   */
  EAttribute getand_the_metric_Integer3();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.when <em>when</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>when</em>'.
   * @see org.unipampa.lesse.xCanopus.when
   * @generated
   */
  EClass getwhen();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.when#getMetrictype <em>Metrictype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Metrictype</em>'.
   * @see org.unipampa.lesse.xCanopus.when#getMetrictype()
   * @see #getwhen()
   * @generated
   */
  EAttribute getwhen_Metrictype();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.then <em>then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>then</em>'.
   * @see org.unipampa.lesse.xCanopus.then
   * @generated
   */
  EClass getthen();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.then#getMetric <em>Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Metric</em>'.
   * @see org.unipampa.lesse.xCanopus.then#getMetric()
   * @see #getthen()
   * @generated
   */
  EAttribute getthen_Metric();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.then#getInteger1 <em>Integer1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integer1</em>'.
   * @see org.unipampa.lesse.xCanopus.then#getInteger1()
   * @see #getthen()
   * @generated
   */
  EAttribute getthen_Integer1();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.then#getInteger2 <em>Integer2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integer2</em>'.
   * @see org.unipampa.lesse.xCanopus.then#getInteger2()
   * @see #getthen()
   * @generated
   */
  EAttribute getthen_Integer2();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.then#getInteger3 <em>Integer3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integer3</em>'.
   * @see org.unipampa.lesse.xCanopus.then#getInteger3()
   * @see #getthen()
   * @generated
   */
  EAttribute getthen_Integer3();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.given <em>given</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>given</em>'.
   * @see org.unipampa.lesse.xCanopus.given
   * @generated
   */
  EClass getgiven();

  /**
   * Returns the meta object for the reference '{@link org.unipampa.lesse.xCanopus.given#getSut1 <em>Sut1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sut1</em>'.
   * @see org.unipampa.lesse.xCanopus.given#getSut1()
   * @see #getgiven()
   * @generated
   */
  EReference getgiven_Sut1();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.given#getSuttype <em>Suttype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Suttype</em>'.
   * @see org.unipampa.lesse.xCanopus.given#getSuttype()
   * @see #getgiven()
   * @generated
   */
  EAttribute getgiven_Suttype();

  /**
   * Returns the meta object for the reference '{@link org.unipampa.lesse.xCanopus.given#getSut2 <em>Sut2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sut2</em>'.
   * @see org.unipampa.lesse.xCanopus.given#getSut2()
   * @see #getgiven()
   * @generated
   */
  EReference getgiven_Sut2();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.SCENARIO <em>SCENARIO</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SCENARIO</em>'.
   * @see org.unipampa.lesse.xCanopus.SCENARIO
   * @generated
   */
  EClass getSCENARIO();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.SCENARIO#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.unipampa.lesse.xCanopus.SCENARIO#getName()
   * @see #getSCENARIO()
   * @generated
   */
  EAttribute getSCENARIO_Name();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.xCanopus.SUT <em>SUT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SUT</em>'.
   * @see org.unipampa.lesse.xCanopus.SUT
   * @generated
   */
  EClass getSUT();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.xCanopus.SUT#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.unipampa.lesse.xCanopus.SUT#getName()
   * @see #getSUT()
   * @generated
   */
  EAttribute getSUT_Name();

  /**
   * Returns the meta object for enum '{@link org.unipampa.lesse.xCanopus.METRICTYPEMONITORED <em>METRICTYPEMONITORED</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>METRICTYPEMONITORED</em>'.
   * @see org.unipampa.lesse.xCanopus.METRICTYPEMONITORED
   * @generated
   */
  EEnum getMETRICTYPEMONITORED();

  /**
   * Returns the meta object for enum '{@link org.unipampa.lesse.xCanopus.METRICTYPE <em>METRICTYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>METRICTYPE</em>'.
   * @see org.unipampa.lesse.xCanopus.METRICTYPE
   * @generated
   */
  EEnum getMETRICTYPE();

  /**
   * Returns the meta object for enum '{@link org.unipampa.lesse.xCanopus.HARDWARE <em>HARDWARE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>HARDWARE</em>'.
   * @see org.unipampa.lesse.xCanopus.HARDWARE
   * @generated
   */
  EEnum getHARDWARE();

  /**
   * Returns the meta object for enum '{@link org.unipampa.lesse.xCanopus.SUT_TYPE <em>SUT TYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>SUT TYPE</em>'.
   * @see org.unipampa.lesse.xCanopus.SUT_TYPE
   * @generated
   */
  EEnum getSUT_TYPE();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XCanopusFactory getXCanopusFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.ModelImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Main</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MAIN = eINSTANCE.getModel_Main();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.MetricModelImpl <em>Metric Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.MetricModelImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getMetricModel()
     * @generated
     */
    EClass METRIC_MODEL = eINSTANCE.getMetricModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METRIC_MODEL__NAME = eINSTANCE.getMetricModel_Name();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METRIC_MODEL__STEPS = eINSTANCE.getMetricModel_Steps();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.MainImpl <em>Main</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.MainImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getMain()
     * @generated
     */
    EClass MAIN = eINSTANCE.getMain();

    /**
     * The meta object literal for the '<em><b>Main</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN__MAIN = eINSTANCE.getMain_Main();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.STEPSImpl <em>STEPS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.STEPSImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getSTEPS()
     * @generated
     */
    EClass STEPS = eINSTANCE.getSTEPS();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.and_workloadImpl <em>and workload</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.and_workloadImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getand_workload()
     * @generated
     */
    EClass AND_WORKLOAD = eINSTANCE.getand_workload();

    /**
     * The meta object literal for the '<em><b>Sut1</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_WORKLOAD__SUT1 = eINSTANCE.getand_workload_Sut1();

    /**
     * The meta object literal for the '<em><b>Suttype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AND_WORKLOAD__SUTTYPE = eINSTANCE.getand_workload_Suttype();

    /**
     * The meta object literal for the '<em><b>Sut2</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_WORKLOAD__SUT2 = eINSTANCE.getand_workload_Sut2();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.and_the_scenarioImpl <em>and the scenario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.and_the_scenarioImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getand_the_scenario()
     * @generated
     */
    EClass AND_THE_SCENARIO = eINSTANCE.getand_the_scenario();

    /**
     * The meta object literal for the '<em><b>Scenario</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_THE_SCENARIO__SCENARIO = eINSTANCE.getand_the_scenario_Scenario();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.and_atleastImpl <em>and atleast</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.and_atleastImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getand_atleast()
     * @generated
     */
    EClass AND_ATLEAST = eINSTANCE.getand_atleast();

    /**
     * The meta object literal for the '<em><b>Integer1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AND_ATLEAST__INTEGER1 = eINSTANCE.getand_atleast_Integer1();

    /**
     * The meta object literal for the '<em><b>Integer2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AND_ATLEAST__INTEGER2 = eINSTANCE.getand_atleast_Integer2();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.and_the_metricImpl <em>and the metric</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.and_the_metricImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getand_the_metric()
     * @generated
     */
    EClass AND_THE_METRIC = eINSTANCE.getand_the_metric();

    /**
     * The meta object literal for the '<em><b>Metric</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AND_THE_METRIC__METRIC = eINSTANCE.getand_the_metric_Metric();

    /**
     * The meta object literal for the '<em><b>Integer1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AND_THE_METRIC__INTEGER1 = eINSTANCE.getand_the_metric_Integer1();

    /**
     * The meta object literal for the '<em><b>Integer2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AND_THE_METRIC__INTEGER2 = eINSTANCE.getand_the_metric_Integer2();

    /**
     * The meta object literal for the '<em><b>Integer3</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AND_THE_METRIC__INTEGER3 = eINSTANCE.getand_the_metric_Integer3();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.whenImpl <em>when</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.whenImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getwhen()
     * @generated
     */
    EClass WHEN = eINSTANCE.getwhen();

    /**
     * The meta object literal for the '<em><b>Metrictype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHEN__METRICTYPE = eINSTANCE.getwhen_Metrictype();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.thenImpl <em>then</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.thenImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getthen()
     * @generated
     */
    EClass THEN = eINSTANCE.getthen();

    /**
     * The meta object literal for the '<em><b>Metric</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute THEN__METRIC = eINSTANCE.getthen_Metric();

    /**
     * The meta object literal for the '<em><b>Integer1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute THEN__INTEGER1 = eINSTANCE.getthen_Integer1();

    /**
     * The meta object literal for the '<em><b>Integer2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute THEN__INTEGER2 = eINSTANCE.getthen_Integer2();

    /**
     * The meta object literal for the '<em><b>Integer3</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute THEN__INTEGER3 = eINSTANCE.getthen_Integer3();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.givenImpl <em>given</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.givenImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getgiven()
     * @generated
     */
    EClass GIVEN = eINSTANCE.getgiven();

    /**
     * The meta object literal for the '<em><b>Sut1</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GIVEN__SUT1 = eINSTANCE.getgiven_Sut1();

    /**
     * The meta object literal for the '<em><b>Suttype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GIVEN__SUTTYPE = eINSTANCE.getgiven_Suttype();

    /**
     * The meta object literal for the '<em><b>Sut2</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GIVEN__SUT2 = eINSTANCE.getgiven_Sut2();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.SCENARIOImpl <em>SCENARIO</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.SCENARIOImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getSCENARIO()
     * @generated
     */
    EClass SCENARIO = eINSTANCE.getSCENARIO();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCENARIO__NAME = eINSTANCE.getSCENARIO_Name();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.impl.SUTImpl <em>SUT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.impl.SUTImpl
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getSUT()
     * @generated
     */
    EClass SUT = eINSTANCE.getSUT();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUT__NAME = eINSTANCE.getSUT_Name();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.METRICTYPEMONITORED <em>METRICTYPEMONITORED</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.METRICTYPEMONITORED
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getMETRICTYPEMONITORED()
     * @generated
     */
    EEnum METRICTYPEMONITORED = eINSTANCE.getMETRICTYPEMONITORED();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.METRICTYPE <em>METRICTYPE</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.METRICTYPE
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getMETRICTYPE()
     * @generated
     */
    EEnum METRICTYPE = eINSTANCE.getMETRICTYPE();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.HARDWARE <em>HARDWARE</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.HARDWARE
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getHARDWARE()
     * @generated
     */
    EEnum HARDWARE = eINSTANCE.getHARDWARE();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.xCanopus.SUT_TYPE <em>SUT TYPE</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.xCanopus.SUT_TYPE
     * @see org.unipampa.lesse.xCanopus.impl.XCanopusPackageImpl#getSUT_TYPE()
     * @generated
     */
    EEnum SUT_TYPE = eINSTANCE.getSUT_TYPE();

  }

} //XCanopusPackage
